<?php include('header.php'); ?>
<div class="grid-x">
<div class="medium-9 cell">
    <h2>Blog Post Title</h2>
    <p><em>Joe Schmoe</em></p>
    <p><em>January 1, 1900</em></p>
    <p>The blog post. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae illum a recusandae quidem aut quas excepturi nam sapiente eaque consectetur, repellendus laudantium, quibusdam ullam, porro maiores omnis alias minima at.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur alias, labore minus adipisci mollitia dolore voluptatibus itaque ut laborum voluptates repellendus illum dignissimos aspernatur, assumenda a recusandae. Facilis, magni, consectetur!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas hic dolore sit atque animi, tempora. Distinctio, culpa ut doloribus aperiam, sunt ipsum a sapiente illum iure quisquam non accusantium quasi.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores amet, omnis rerum veniam sunt suscipit impedit necessitatibus accusamus, repudiandae doloremque accusantium laboriosam ut laudantium doloribus obcaecati, non sed eos facilis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi praesentium esse repellat laborum voluptatibus quas atque excepturi eveniet deleniti minus. Unde natus perspiciatis eveniet impedit repellendus tenetur magni ullam pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum repudiandae totam nemo ipsa quod, quidem omnis nam distinctio eos accusamus nisi officiis atque, ad aperiam inventore aut! Odio, fugit, temporibus!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam officia sit doloremque nihil, repellendus excepturi. Nihil enim facere dolorem nulla dignissimos a similique quidem autem, odio assumenda. Fugit, earum, delectus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis quod recusandae sit, dolorum iure nisi repellendus perferendis consectetur veniam, necessitatibus dolorem sequi totam hic non fugiat, repellat earum inventore voluptatibus!</p>

    <img src="https://via.placeholder.com/1500x450?text=IMAGE" alt="">

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores amet, omnis rerum veniam sunt suscipit impedit necessitatibus accusamus, repudiandae doloremque accusantium laboriosam ut laudantium doloribus obcaecati, non sed eos facilis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi praesentium esse repellat laborum voluptatibus quas atque excepturi eveniet deleniti minus. Unde natus perspiciatis eveniet impedit repellendus tenetur magni ullam pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum repudiandae totam nemo ipsa quod, quidem omnis nam distinctio eos accusamus nisi officiis atque, ad aperiam inventore aut! Odio, fugit, temporibus!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam officia sit doloremque nihil, repellendus excepturi. Nihil enim facere dolorem nulla dignissimos a similique quidem autem, odio assumenda. Fugit, earum, delectus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis quod recusandae sit, dolorum iure nisi repellendus perferendis consectetur veniam, necessitatibus dolorem sequi totam hic non fugiat, repellat earum inventore voluptatibus!</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores amet, omnis rerum veniam sunt suscipit impedit necessitatibus accusamus, repudiandae doloremque accusantium laboriosam ut laudantium doloribus obcaecati, non sed eos facilis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi praesentium esse repellat laborum voluptatibus quas atque excepturi eveniet deleniti minus. Unde natus perspiciatis eveniet impedit repellendus tenetur magni ullam pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum repudiandae totam nemo ipsa quod, quidem omnis nam distinctio eos accusamus nisi officiis atque, ad aperiam inventore aut! Odio, fugit, temporibus!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam officia sit doloremque nihil, repellendus excepturi. Nihil enim facere dolorem nulla dignissimos a similique quidem autem, odio assumenda. Fugit, earum, delectus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis quod recusandae sit, dolorum iure nisi repellendus perferendis consectetur veniam, necessitatibus dolorem sequi totam hic non fugiat, repellat earum inventore voluptatibus!</p>
    
    <div class="grid-x grid-margin-x">
    <div class="medium-4 cell"><img src="https://via.placeholder.com/500x500?text=IMAGE" alt=""></div>
    <div class="medium-4 cell"><img src="https://via.placeholder.com/500x500?text=IMAGE" alt=""></div>
    <div class="medium-4 cell"><img src="https://via.placeholder.com/500x500?text=IMAGE" alt=""></div>
    </div>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores amet, omnis rerum veniam sunt suscipit impedit necessitatibus accusamus, repudiandae doloremque accusantium laboriosam ut laudantium doloribus obcaecati, non sed eos facilis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi praesentium esse repellat laborum voluptatibus quas atque excepturi eveniet deleniti minus. Unde natus perspiciatis eveniet impedit repellendus tenetur magni ullam pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum repudiandae totam nemo ipsa quod, quidem omnis nam distinctio eos accusamus nisi officiis atque, ad aperiam inventore aut! Odio, fugit, temporibus!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam officia sit doloremque nihil, repellendus excepturi. Nihil enim facere dolorem nulla dignissimos a similique quidem autem, odio assumenda. Fugit, earum, delectus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis quod recusandae sit, dolorum iure nisi repellendus perferendis consectetur veniam, necessitatibus dolorem sequi totam hic non fugiat, repellat earum inventore voluptatibus!</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores amet, omnis rerum veniam sunt suscipit impedit necessitatibus accusamus, repudiandae doloremque accusantium laboriosam ut laudantium doloribus obcaecati, non sed eos facilis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi praesentium esse repellat laborum voluptatibus quas atque excepturi eveniet deleniti minus. Unde natus perspiciatis eveniet impedit repellendus tenetur magni ullam pariatur.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum repudiandae totam nemo ipsa quod, quidem omnis nam distinctio eos accusamus nisi officiis atque, ad aperiam inventore aut! Odio, fugit, temporibus!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam officia sit doloremque nihil, repellendus excepturi. Nihil enim facere dolorem nulla dignissimos a similique quidem autem, odio assumenda. Fugit, earum, delectus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis quod recusandae sit, dolorum iure nisi repellendus perferendis consectetur veniam, necessitatibus dolorem sequi totam hic non fugiat, repellat earum inventore voluptatibus!</p>
</div>
</div>
<?php include('footer.php'); ?>